apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "connect-go-boilerplate.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "connect-go-boilerplate.name" . }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.connectGoBoilerplate.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "connect-go-boilerplate.name" . }}
      release: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app: {{ include "connect-go-boilerplate.name" . }}
        release: {{ .Release.Name | quote }}
    spec:
      {{- if .Values.connectGoBoilerplate.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.connectGoBoilerplate.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.connectGoBoilerplate.image.registry }}/{{ .Values.connectGoBoilerplate.image.repository }}:{{ .Values.connectGoBoilerplate.image.tag }}"
        imagePullPolicy: {{ .Values.connectGoBoilerplate.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.connectGoBoilerplate.service.targetPort }}
          protocol: TCP
        {{- if .Values.connectGoBoilerplate.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.connectGoBoilerplate.livenessProbe | nindent 12 }}
        {{- end }}
        {{- if .Values.connectGoBoilerplate.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.connectGoBoilerplate.readinessProbe | nindent 12 }}
        {{- end }}
        {{- with .Values.connectGoBoilerplate.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
