{{- if .Values.gateway.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default "envoy-gateway" }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.port | default 30080 }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
