{{- if .Values.keycloak.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "connect-go-boilerplate.fullname" . }}-http
  namespace: {{ .Release.Namespace | quote }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: {{ .Values.keycloak.name }}-service
          port: {{ .Values.keycloak.service.port }}
{{- end }}
