apiVersion: v1
kind: Secret
metadata:
  name: harbor-secret
  namespace: { { .Release.Namespace | quote } }
  labels:
    app: { { include "connect-go-boilerplate.name" . } }
    release: { { .Release.Name | quote } }
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:
    { { include "connect-go-boilerplate.dockercfg" . | b64enc } }
