{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.db.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
data:
{{- if .Values.postgresql.enabled }}
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
{{- else }}
  username: {{ .Values.keycloak.db.username | b64enc | quote }}
  password: {{ .Values.keycloak.db.password | b64enc | quote }}
{{- end }}
{{- end }}
