{{- if .Values.keycloak.enabled -}}
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: {{ .Values.keycloak.realm.name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  keycloakCRName: {{ .Values.keycloak.name }}
  realm:
{{ .Files.Get "files/keycloak-realm.json" | indent 4 }}
{{- end }}
