{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.admin.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.keycloak.admin.username }}
  password: {{ .Values.keycloak.admin.password }}
{{- end }}
