{{- if .Values.keycloak.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.db.secretName }}
  namespace: {{ .Release.Namespace | quote }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.db.username }}
  password: {{ .Values.keycloak.db.password }}
{{- end }}
