apiVersion: v1
kind: Service
metadata:
  name: {{ include "connect-go-boilerplate.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "connect-go-boilerplate.name" . }}
    release: {{ .Release.Name | quote }}
spec:
  type: {{ .Values.connectGoBoilerplate.service.type }}
  ports:
    - port: {{ .Values.connectGoBoilerplate.service.port }}
      targetPort: {{ .Values.connectGoBoilerplate.service.targetPort }}
      {{- if eq .Values.connectGoBoilerplate.service.type "NodePort" }}
      nodePort: {{ .Values.connectGoBoilerplate.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: {{ .Values.connectGoBoilerplate.service.name }}
  selector:
    app: {{ include "connect-go-boilerplate.name" . }}
    release: {{ .Release.Name | quote }}
